### ISSUE TITLE
QA_To Study the operational details of a CD spectrometer_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#100]
Defect Description :
In the "To Study the operational details of a CD spectrometer" experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the "To Study the operational details of a CD spectrometer" experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i60](https://cloud.githubusercontent.com/assets/13479177/26710649/25bbeb70-4779-11e7-8fac-8f048c191f15.png)

**Comment by sravanthimodepu** [comment]
Simulation is enabled on the small screen. Hence differing the issue.

**Comment by BSravanthi** [comment]
Not a differed issue. Though the experiment works with java or not it does not make any difference in enabling the small screen.

**Comment by BSravanthi** [comment]
Closed #100 as the issue got resolved.
