### ISSUE TITLE
QA_To Study the effect of Secondary Structure elements on CD spectrum of proteins_Experiment_functionality-of-Step by step mode button

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#103]
Defect Description :
In the "To Study the effect of Secondary Structure elements on CD spectrum of proteins" experiment, the functionality of the "Step by step mode" button is not present.

Actual Result :
In the "To Study the effect of Secondary Structure elements on CD spectrum of proteins" experiment, the functionality of the "Step by step mode" button is not present. No further step is performing on click of the button.

In the given attachment on click "Exit Simulation", redirecting to error page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i62](https://cloud.githubusercontent.com/assets/13479177/26711286/edee4806-477c-11e7-9eb5-4da99302475e.png)

**Comment by sravanthimodepu** [comment]
Need to make changes inside the simulation. Hence keeping the issue on hold
