### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_all sections_bread-crumb-overlaps-bookmark-button

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#104]
Defect Description :
In all the sections of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements " experiment of this lab, the bread crump is overlapping the bookmarks button.

Actual Result :
In all the sections of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements " experiment of this lab, the bread crump is overlapping the bookmarks button.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i63](https://cloud.githubusercontent.com/assets/13479177/26711366/7b9d28f2-477d-11e7-82ba-42b3863009c0.png)

**Comment by sravanthimodepu** [comment]
Issue is keeping on hold.
