### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#105]
Defect Description :
In the "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i65](https://cloud.githubusercontent.com/assets/13479177/26711544/aad24958-477e-11e7-9c98-2c093ed61721.png)

**Comment by sravanthimodepu** [comment]
Simulation is displaying on the small screen. Hence differing the issue.
![deconv](https://user-images.githubusercontent.com/11156924/27767671-4810e0e4-5f1c-11e7-99db-32ea668e1a0d.png)

**Comment by BSravanthi** [comment]
Closed #105
