### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Experiment_unwanted-letters-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#106]
Defect Description :
Found unwanted letter in the small screen section of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment.

Actual Result :
Found unwanted letter in the small screen section of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i64](https://cloud.githubusercontent.com/assets/13479177/26711590/04e22648-477f-11e7-911c-e3a15d1c8dc8.png)

**Comment by sravanthimodepu** [comment]
Removed unwanted text from the experiment page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #106
