### ISSUE TITLE
QA_To study the thermal stability of proteins_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#107]
Defect Description :
In the "To study the thermal stability of proteins" experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the "To study the thermal stability of proteins" experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i66](https://cloud.githubusercontent.com/assets/13479177/26711664/ac58fe42-477f-11e7-9fbf-b907aab6aec1.png)

**Comment by sravanthimodepu** [comment]
Simulation is displaying on the small screen. Hence differing the issue.
![thermal](https://user-images.githubusercontent.com/11156924/27767661-f5946444-5f1b-11e7-9dea-b93446eca5c1.png)

**Comment by BSravanthi** [comment]
Not a differed issue. Though the experiment works with java or not it does not make any difference in enabling the small screen.

**Comment by BSravanthi** [comment]
Closed #107 as the issue got resolved.
