### ISSUE TITLE
QA_To study the thermal stability of proteins_Experiment_improper-numbering-in-quiz

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#108]
Defect Description :
In the experiment page of "To study the thermal stability of proteins", numbering of the quiz section is given wrong.

Actual Result :
In the experiment page of "To study the thermal stability of proteins", numbering of the quiz section is given wrong.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i67](https://cloud.githubusercontent.com/assets/13479177/26712071/73fc9e5c-4782-11e7-9fe1-e5ef03401419.png)

**Comment by sravanthimodepu** [comment]
Given proper numbering for the quiz questions. Actual quiz section has Click here link which redirects to the quiz questions , instead added the quiz questions in the quiz section without consistency.
Hence resolved the issue.

**Comment by BSravanthi** [comment]
I did not give a detailed direction to navigate to the quiz page in the experiment section,
The quiz section will appear once we finish the experiment of 1 st step.
There the numbering for the questions are improper. 
The issue is reopened as the numbering is not corrected.
