### ISSUE TITLE
QA_To study the effect of chemical denaturants on protein stability_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#110]
Defect Description :
In the "To study the effect of chemical denaturants on protein stability" experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the "To study the effect of chemical denaturants on protein stability" experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i69](https://cloud.githubusercontent.com/assets/13479177/26712665/a06d1ae0-4785-11e7-85e2-acccd4bff26d.png)

**Comment by sravanthimodepu** [comment]
Simulation is displaying on the small screen. Hence differing the issue.
![chem](https://user-images.githubusercontent.com/11156924/27767648-b2972bfe-5f1b-11e7-90f8-51f4dca278dd.png)

**Comment by BSravanthi** [comment]
Not a differed issue. Though the experiment works with java or not it does not make any difference in enabling the small screen.

**Comment by BSravanthi** [comment]
Closed #110 as the issue got resolved.
