### ISSUE TITLE
QA_To study the effect of chemical denaturants on protein stability_Experiment_Functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#113]
Defect Description :
In the experiment page of "To study the effect of chemical denaturants on protein stability", the functionality of the experiment is improper. When we try to reset the experiment in the middle of the experiment, all the apparatus are not appearing in the experiment. 

Actual Result :
In the experiment page of "To study the effect of chemical denaturants on protein stability", the functionality of the experiment is improper. When we try to reset the experiment in the middle of the experiment, all the apparatus are not appearing in the experiment. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i73](https://cloud.githubusercontent.com/assets/13479177/26713822/25e90b4c-478c-11e7-80bf-e3364b891745.png)

**Comment by sravanthimodepu** [comment]
As the simulation is running with flash, we cannot make any changes to it. Hence the issue is onhold.
