### ISSUE TITLE
QA_To study the effect of chemical denaturants on protein stability_Experiment_Sprectrophotometer-Functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#114]
Defect Description :
In the experiment page of "To study the effect of chemical denaturants on protein stability", the functionality of the spectrophotometer is improper. Found discrepancy in the functionality. The meter is accessible before the preparation of the solution in the cuvvette.  

Actual Result :
In the experiment page of "To study the effect of chemical denaturants on protein stability", the functionality of the spectrophotometer is improper. Found discrepancy in the functionality. The meter is accessible before the preparation of the solution in the cuvvette.  

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i72](https://cloud.githubusercontent.com/assets/13479177/26714521/64d19362-478f-11e7-8561-b68cceb0e413.png)

**Comment by sravanthimodepu** [comment]
As the simulation is running with flash, we cannot make any changes to it. Hence issue is onhold.
