### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing _Experiment_disabled-in-small-scree

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#115]
Defect Description :
In the "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing " experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing " experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i74](https://cloud.githubusercontent.com/assets/13479177/26714576/b09d303a-478f-11e7-9aed-c44a2fce345d.png)

**Comment by sravanthimodepu** [comment]
Simulation is displaying on the small screen. Hence differing the issue.
![comp](https://user-images.githubusercontent.com/11156924/27767635-5082e584-5f1b-11e7-965e-03cf88b1f10e.png)

**Comment by BSravanthi** [comment]
Not a differed issue. Though the experiment works with java or not it does not make any difference in enabling the small screen.

**Comment by BSravanthi** [comment]
Closed #115 as the issue got resolved.
