### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing _all sections_bread-crup-overlaps-bookmark-button

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#116]
Defect Description :
In all the sections of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing" experiment of this lab, the bread crump is overlapping the bookmarks button.

Actual Result :
In all the sections of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing " experiment of this lab, the bread crump is overlapping the bookmarks button.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i74](https://cloud.githubusercontent.com/assets/13479177/26714637/00a17140-4790-11e7-9e50-9a2828248c51.png)

**Comment by sravanthimodepu** [comment]
Issue is keeping on hold.
