### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing _Experiment_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#117]
Defect Description :
In the Experiment section of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing" experiment, when click on "Sample 1" and "Sample 2" buttons links are navigating to an error pages. Hence unable to perform the experiment. Where as on click "compare" button, the link is navigating to quiz page.

Actual Result :
In the Experiment section of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing" experiment, when click on "Sample 1" and "Sample 2" buttons links are navigating to an error pages. Hence unable to perform the experiment. Where as on click "compare" button, the link is navigating to quiz page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i75](https://cloud.githubusercontent.com/assets/13479177/26714731/7a95a8fe-4790-11e7-894d-5554b5aa2537.png)

**Comment by sravanthimodepu** [comment]
Assigned the appropriate link for the experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue closed #117
