### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing_Experiment_improper-numbering-in-quiz

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#118]
Defect Description :
In the experiment page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing ", numbering of the quiz section is improper.

Actual Result :
In the experiment page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing ", numbering of the quiz section is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i76](https://cloud.githubusercontent.com/assets/13479177/26714897/213a13ca-4791-11e7-9234-42de5cb68ce7.png)

**Comment by sravanthimodepu** [comment]
Given proper numbering for the quiz questions. Actual quiz section has **Click here** link which redirects to the quiz questions , instead added the quiz questions in the quiz section without consistency.
Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue still persisted as the described bug is in the experiment's quiz page. Hence re opening the issue.
