### ISSUE TITLE
QA_To study the effect of chemical denaturants on protein stability_UI_of_Quiz_section

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/circular-dichronism-spectroscopy-iiith#119]
Defect Description :
In the experiment page of "To study the effect of chemical denaturants on protein stability ", numbering of the quiz section is improper.

Actual Result :
In the experiment page of "To study the effect of chemical denaturants on protein stability ", numbering of the quiz section is improper.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:

**Comment by sravanthimodepu** [comment]
Given proper numbering for the quiz questions. Actual quiz section has Click here link which redirects to the quiz questions , instead added the quiz questions in the quiz section without consistency.
Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue still persisted as the issue is related to experiments quiz page.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence differing the issue.
![chem-denat](https://user-images.githubusercontent.com/11156924/27790519-67b3fda8-600e-11e7-9079-b4589eceb1d7.png)

**Comment by BSravanthi** [comment]
Not a differed issue.
