### ISSUE TITLE
QA_To determine the specific rotation of a sugar using a polarimeter_Experiment_unwanted-text

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#120]
Defect Description :
While testing #38, found unwanted text near the small screen of the Simulation of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab.

Actual Result :
While testing #38, found unwanted text near the small screen of the Simulation of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i78](https://user-images.githubusercontent.com/13479177/27672114-4502e9f0-5cb6-11e7-98e9-22df05c551e5.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence resolved the issue.
![spec-rot](https://user-images.githubusercontent.com/11156924/27767279-553e011e-5f0f-11e7-9550-7e5fc08b7754.png)

**Comment by BSravanthi** [comment]
Closed #120
