### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Manual_unwanted_Unit

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#127]
Defect Description :
In the Manual page of the "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment, unwanted unit has provided with no content.

Actual Result :
In the Manual page of the "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment, unwanted unit has provided with no content.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i86](https://user-images.githubusercontent.com/13479177/27675974-cdbd8a1c-5cc9-11e7-8e87-018b88ebe1ed.png)

**Comment by sravanthimodepu** [comment]
Removed the extra the unit.. Hence resolved the issue.
![cd-manual](https://user-images.githubusercontent.com/11156924/27763372-2743725e-5ea0-11e7-9045-59da27695310.png)

**Comment by BSravanthi** [comment]
Closed #127
