### ISSUE TITLE
QA_To determine the specific rotation of a sugar using a polarimeter_Introduction_Broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#13]
**Defect Description** :
In the introduction page of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, mentioned two links are redirecting to an error page showing "Page not found". Where as the links should redirect to the appropriate pages.

**Actual Result** :
In the introduction page of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, mentioned two links are redirecting to an error page showing "Page not found". 

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_intro 1 _link_i1](https://cloud.githubusercontent.com/assets/13479177/18949732/06882690-8656-11e6-84e5-6f695ea3e207.png)

**Comment by sravanthimodepu** [comment]
Removed the links, as they are redirecting to the error page.

**Comment by BSravanthi** [comment]
Closed #13
