### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing _Experiment_small-screen-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#130]
While testing #117 found that the alignment of the small screen is improper. 

![qa_oe_cds_i89](https://user-images.githubusercontent.com/13479177/27785877-a1898a0a-5ffc-11e7-95b4-f80fa2eb797b.png)

**Comment by sravanthimodepu** [comment]
Added scroll bar to the simulation to view it in a better view. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #130
