### ISSUE TITLE
QA_To determine the specific rotation of a sugar using a polarimeter_Further readings_broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#14]
**Defect Description** :
In the Further readings page of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab.. 1st, 4th and 5th links are redirecting to an error page showing "Page not found". Where as the links should redirect to the appropriate pages.

**Actual Result** :
In the Further readings page of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab.. 1st, 4th and 5th links links are redirecting to an error page showing "Page not found".

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_fr 1 _links_i2](https://cloud.githubusercontent.com/assets/13479177/18949916/e6ee54e8-8656-11e6-8cee-cee183594be3.png)

**Comment by sravanthimodepu** [comment]
Removing 4th & 5th links as they are redirecting to the error page and assign proper link fo the 1st link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #14
