### ISSUE TITLE
QA_To understand the effect of chiral substances on plane polarized light as a function of wavelength_Theory_broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#15]
**Defect Description** :
In the Theory page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab, the Experiment 1 links are given twice in the content. These links are redirecting to error saying page not found. Where as the links should redirect to the appropriate page.
Even the links given along with the animations and the images are also broken.

**Actual Result** :
In the Theory page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab, the Experiment 1 links are given twice in the content. These links are redirecting to error saying page not found.
Even the links given along with the animations and the images are also broken.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_theory 2 _links_i3](https://cloud.githubusercontent.com/assets/13479177/18950160/013c8062-8658-11e6-9dae-9c56d3ee0803.png)

**Comment by sravanthimodepu** [comment]
Tried to fix the issue but there is no related link. Hence unassigned the link as it is redirecting to the error page and resolved the issue.

**Comment by BSravanthi** [comment]
Not a differed issue. And as resolved, the issue #15 is closed
