### ISSUE TITLE
QA_To understand the effect of chiral substances on plane polarized light as a function of wavelength_Quiz_junk characters

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#16]
**Defect Description** :
In the Quizzes page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab,Junk characters are present. Remove these junk characters to maintain the look and feel of the page.

**Actual Result** :
In the Quizzes page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab, Junk characters are present. 

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments:**
![qa_cds_quiz 2 _i4](https://cloud.githubusercontent.com/assets/13479177/18950826/66b18d0e-865b-11e6-9586-08d90d1aeaa1.png)

**Comment by sravanthimodepu** [comment]
As all the labs are moved to open-edx,  UI of all the quiz is changed. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #16
