### ISSUE TITLE
QA_To understand the effect of chiral substances on plane polarized light as a function of wavelength_Further readings_broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#17]
**Defect Description** :
In the further References page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab, the 2nd and 3rd links are redirecting to error saying page not found. Where as the links should redirect to the appropriate page.

**Actual Result** :
In the further References page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab, the 2nd and 3rd links are redirecting to error saying page not found.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_fr 2 _i5](https://cloud.githubusercontent.com/assets/13479177/18951477/dada4506-865e-11e6-92d5-1b8885831a7a.png)

**Comment by sravanthimodepu** [comment]
As the 2nd link is not working, assigned the related link to it. For the 3rd link, there is mistake in the link, corrected it. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #17
