### ISSUE TITLE
QA_To study the Optical Rotatory Dispersion (ORD) of some chiral substances_Further readings_broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#18]
**Defect Description** :
In the Further readings page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, the 1st link is redirecting to error saying page not found. Where as the links should redirect to the appropriate page.

**Actual Result** :
In the Further readings page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, the 1st link is redirecting to error saying page not found.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_fr 3 _i6](https://cloud.githubusercontent.com/assets/13479177/18951626/969c4802-865f-11e6-85f8-6af0bca5db5e.png)

**Comment by sravanthimodepu** [comment]
As the link is redirecting to an error page, assigned the related link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #18
