### ISSUE TITLE
QA_To Study the effect of Secondary Structure elements on CD spectrum of proteins_Further readings_broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#24]
**Defect Description** :
In the further References page of "To Study the effect of Secondary Structure elements on CD spectrum of proteins" experiment in this lab, the 2nd, 3rd links are links are redirecting to error saying page not found. Where as the links should redirect to the appropriate page.

**Actual Result** :
In the further References page of "To Study the effect of Secondary Structure elements on CD spectrum of proteins" experiment in this lab, the 2nd, 3rd links are links are redirecting to error saying page not found. 

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_fr 6 _i16](https://cloud.githubusercontent.com/assets/13479177/18982314/9c626d76-86fe-11e6-82f3-41a1600fbfc6.png)

**Comment by sravanthimodepu** [comment]
Corrected the links. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #24
