### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Introduction_Broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#25]
**Defect Description** :
In the introduction page of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, the **Experiment6** link is redirecting to an error page showing "Page not found". Where as the links should redirect to the appropriate pages.

**Actual Result** :
In the introduction page of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, the **Experiment6** link is redirecting to an error page showing "Page not found". 

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_intro 7 _i17](https://cloud.githubusercontent.com/assets/13479177/18982523/4b3ee01c-8700-11e6-862a-a39f7de0bd07.png)

**Comment by BSravanthi** [comment]
Observed that the other link provided in the introduction page is also broken.

**Comment by sravanthimodepu** [comment]
Unassigned the  **Experiment 6** link and assigned the related link for the other broken. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #25
