### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Further readings_broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#26]
**Defect Description** :
In the further References page of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, both the links in 1st point,  are redirecting to error saying page not found. Where as the links should redirect to the appropriate page.

**Actual Result** :
In the further References page of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, both the links in 1st point,  are redirecting to error saying page not found.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_fr 7 _i18](https://cloud.githubusercontent.com/assets/13479177/18982896/010e1a32-8703-11e6-95b4-936d25813222.png)
![qa_cds_fr 7 _i19](https://cloud.githubusercontent.com/assets/13479177/18982929/40af705a-8703-11e6-8812-8ff15abe3894.png)

**Comment by sravanthimodepu** [comment]
Assigned the appropriate links in the further readings. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #26
