### ISSUE TITLE
QA_To Study the Thermal Stability of Proteins_Further readings_broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#29]
**Defect Description** :
In the further References page of "To Study the Thermal Stability of Proteins" experiment in this lab, the attached link is redirecting to error saying page not found. Where as the links should redirect to the appropriate page.

**Actual Result** :
In the further References page of "To Study the Thermal Stability of Proteins" experiment in this lab, the attached link is redirecting to error saying page not found.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_fr 7 _i23](https://cloud.githubusercontent.com/assets/13479177/18984012/7f7b0b54-8709-11e6-940f-3ee9894e4754.png)

**Comment by sravanthimodepu** [comment]
Assigned the appropriate link in the further readings. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #29
