### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents_Manual_Video not included

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#32]
**Defect Description** :
In the Manual page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, the given video section is not included with the video. Even when we click on we Enlarge button, the page is taking long time to load/ in fact the page is not opening. Where as the video should be included for the convenience of the user.

**Actual Result** :
In the Manual page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, the given video section is not included with the video. Even when we click on we Enlarge button, the page is taking long time to load/ in fact the page is not opening.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_manu 10 _i26](https://cloud.githubusercontent.com/assets/13479177/18986790/f335f668-8717-11e6-9c0c-edddafc72ea2.png)

**Comment by sravanthimodepu** [comment]
Updated the video in the manual page of this experiment from vlab.co.in . Hence resolved the issue'.

**Comment by BSravanthi** [comment]
Issue is fixed. The issue is re opening as the alignment of the video is improper.

**Comment by sravanthimodepu** [comment]
Uploaded the video, hence differing this issue.
![comp-man](https://user-images.githubusercontent.com/11156924/27825576-a1b4a56a-60cd-11e7-8870-604190da4f0f.png)
