### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents_Further readings_longer-loading-time

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#33]
**Defect Description** :
In the further References page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, the attached link is taking too long time to load. Where as the links should not take much time to open.

**Actual Result** :
In the further References page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, the attached link is taking too long time to load.

**Environment** :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

**Attachments**:
![qa_cds_fr 10 _i27](https://cloud.githubusercontent.com/assets/13479177/18987193/f53a81ac-8719-11e6-8231-c0eceb7caebb.png)

**Comment by sravanthimodepu** [comment]
Assigned the appropriate for the broke link in the further readings page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #33
