### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents_Experiment_Broken links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#35]
Defect Description :
In the Experiment page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, both the experiment links are broken and are navigating to error message page. Instead the links should be navigating to the concerned experiments page, where the user should be able to perform the experiment. 

Actual Result :
In the Experiment page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, both the experiment links are broken and are navigating to error message page. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_expt10_i28](https://cloud.githubusercontent.com/assets/13479177/25171656/2e84d760-250c-11e7-8e06-87d5dd0767c0.png)

**Comment by sravanthimodepu** [comment]
There is some mistake in the simulation URL, corrected the link to run he simulation. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #35
