### ISSUE TITLE
QA_Circular Dichroism Spectroscopy_Introduction_Target Audiance_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#36]
Defect Description :
In the Sub section "Target Audience" of Introduction section of this lab, found spelling mistakes. 
  
Actual Result :
In the Sub section "Target Audience" of Introduction section of this lab, found spelling mistakes. 
Audience spelling is given mistakenly. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i01](https://cloud.githubusercontent.com/assets/13479177/26536416/4d25232a-4454-11e7-84e5-4226cfc9f7bf.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #36
