### ISSUE TITLE
QA_To determine the specific rotation of a sugar using a polarimeter_Theory_image-to-be-ported-properly

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#37]
Defect Description :
In the Theory page of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, The two images and an animation given are needs to be ported properly.

Actual Result :
In the Theory page of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, The two images and an animation given are needs to be ported properly. The width of the images and the animation is varying due to which the visibility of the same is not good.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i02](https://cloud.githubusercontent.com/assets/13479177/26536999/542d1f7e-4459-11e7-8f8e-5dedf83166ea.png)

**Comment by sravanthimodepu** [comment]
Adjusted the width of the images to view in a better way. Hence resolved the issue.

**Comment by BSravanthi** [comment]
The issue is still not fixed. In fact the whole theory page content has been shrunk.  Hence reopened the issue. 
Please find the attached

![qa_oe_cds_i77](https://user-images.githubusercontent.com/13479177/27671941-4b6b2de4-5cb5-11e7-814e-33098f9cc45f.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Reopened 
PFA

![qa_oe_cds_i91](https://user-images.githubusercontent.com/13479177/27787131-75b7598e-6001-11e7-9b74-d0fd2a2fa90b.png)
![qa_oe_cds_i92](https://user-images.githubusercontent.com/13479177/27787128-7511c136-6001-11e7-8985-6fe1b5ae4d1a.png)

**Comment by sravanthimodepu** [comment]
Fixed.
![sugar-theory](https://user-images.githubusercontent.com/11156924/27827034-06879eca-60d3-11e7-8baa-dcdc14596301.png)
