### ISSUE TITLE
QA_To determine the specific rotation of a sugar using a polarimeter_Experiment_to-be-ported

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#38]
Defect Description :
In the Simulation of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, the experiment needs to be ported. 

Actual Result :
In the Simulation of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, the experiment needs to be ported. Even the bread crump is also missed. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i03](https://cloud.githubusercontent.com/assets/13479177/26537167/a0b0301a-445a-11e7-9c4d-65c7422c32bf.png)

**Comment by sravanthimodepu** [comment]
Ported the experiment from vlab.co.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #38
