### ISSUE TITLE
QA_To determine the specific rotation of a sugar using a polarimeter_Manual_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#39]
Defect Description :
In the Simulation of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, the alignment of the numbering is improper.

Actual Result :
In the Simulation of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, the alignment of the numbering is improper.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i04](https://cloud.githubusercontent.com/assets/13479177/26537273/949c6aa4-445b-11e7-820e-49ddad6948f0.png)

**Comment by sravanthimodepu** [comment]
Aligned the content properly with numbers. Hence resolved the issue.

**Comment by BSravanthi** [comment]
The issue is still open as the content is exceeding the screen. Hence re-opening the issue.

**Comment by sravanthimodepu** [comment]
Fixed.
