### ISSUE TITLE
QA_To determine the specific rotation of a sugar using a polarimeter_Quizzes 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#40]
Defect Description :
In the Quiz page of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, instead of giving a link, need to import the quiz unit directly by using the problem component.

Actual Result :
In the Quiz page of "To determine the specific rotation of a sugar using a polarimeter" experiment in this lab, instead of giving a link, need to import the quiz unit directly by using the problem component.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments: 
![qa_oe cds_i05](https://cloud.githubusercontent.com/assets/13479177/26537390/b28125a4-445c-11e7-8b09-82784a064ea8.png)

**Comment by sravanthimodepu** [comment]
Ported the quiz directly to the quiz section instead of link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #40
