### ISSUE TITLE
QA_order-of-the-menu_To determine the specific rotation of a sugar using a polarimeter

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#41]
Defect Description :
The order of the menu items for this lab should be changed to "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback". 

Actual Result :
The order of the menu items for this experiment is given as "Introduction, theory, objective, experiment, manual, quizzes and further readings".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i06](https://cloud.githubusercontent.com/assets/13479177/26537500/c094ed50-445d-11e7-8d22-010956f97f8a.png)

**Comment by sravanthimodepu** [comment]
The order of the menu is updated as "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback" in this experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #41
