### ISSUE TITLE
QA_To understand the effect of chiral substances on plane polarized light as a function of wavelength_Menu-items_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#43]
Defect Description :
Found spelling mistakes in the menu items of "To understand the effect of chiral substances on plane polarized light as a function of wavelength"experiment this lab. 

Actual Result :
Found spelling mistakes in the menu items of "To understand the effect of chiral substances on plane polarized light as a function of wavelength"experiment this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i08](https://cloud.githubusercontent.com/assets/13479177/26537791/da3f0b1c-445f-11e7-9ee6-942ced140d37.png)

**Comment by sravanthimodepu** [comment]
Corrected the menu spelling mistakes of this experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #43
