### ISSUE TITLE
QA_To understand the effect of chiral substances on plane polarized light as a function of wavelength_Theory_improper-porting-of-images

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#44]
Defect Description :
In the Theory page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab, The images are shrunk.  

Actual Result :
In the Theory page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab, The images are shrunk.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i09](https://cloud.githubusercontent.com/assets/13479177/26538044/64b7a2f8-4461-11e7-8564-f8c01e014038.png)

**Comment by sravanthimodepu** [comment]
As the images are inside the table tags, they are looking as shrunken. Hence removes the table tags for images and resolved the issue.

**Comment by BSravanthi** [comment]
Closed #44
