### ISSUE TITLE
QA_To understand the effect of chiral substances on plane polarized light as a function of wavelength_Manual_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#45]
Defect Description :
Found spelling mistakes in the manual section of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment this lab.

Actual Result :
Found spelling mistakes in the manual section of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i10](https://cloud.githubusercontent.com/assets/13479177/26538132/f3bd32b0-4461-11e7-932f-fc915009c08f.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the manual page of this experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #45

**Comment by BSravanthi** [comment]
Issue re opened as the spelling of Introduction yet to be corrected.
