### ISSUE TITLE
QA_To study the Optical Rotatory Dispersion (ORD) of some chiral substances_Theory_image-needs-to-be-ported-properly 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#47]
Defect Description :
In the Theory page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, while porting, the 1st and 2nd images have been shrunk.

Actual Result :
In the Theory page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, while porting, the 1st and 2nd images have been shrunk.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i12](https://cloud.githubusercontent.com/assets/13479177/26538711/10303a7e-4466-11e7-88e8-236de4cdb001.png)

**Comment by sravanthimodepu** [comment]
Images are inserted inside the table tags, hence removed table tags for the images and adjusted width to view in a better way. Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #47
