### ISSUE TITLE
QA_To study the Optical Rotatory Dispersion (ORD) of some chiral substances_Objective_numbering-&-alignment-is-improper

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#49]
Defect Description :
In the Objective page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, the numbering and alignment of the content is improper after porting. Where as in the vlabs page, every thing was fine. 

Actual Result :
In the Objective page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, the numbering and alignment of the content is improper after porting. Where as in the vlabs page, every thing was fine.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i14](https://cloud.githubusercontent.com/assets/13479177/26539313/6c16314c-4469-11e7-9d55-fccfd10d0b84.png)

**Comment by sravanthimodepu** [comment]
Aligned the content in order with proper numbering. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #49
