### ISSUE TITLE
QA_To study the Optical Rotatory Dispersion (ORD) of some chiral substances_Manual_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#50]
Defect Description :
Found spelling mistakes in the Manual section of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment this lab.

Actual Result :
Found spelling mistakes in the Manual section of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i15](https://cloud.githubusercontent.com/assets/13479177/26539407/deb52c44-4469-11e7-9f61-e384294a2048.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the manual page of this experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #50
