### ISSUE TITLE
QA_To study the Optical Rotatory Dispersion (ORD) of some chiral substances_Manual_improper-numbering

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#51]
Defect Description :
In the Manual page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, after porting the numbering of the points is incorrect.  

Actual Result :
In the Manual page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, after porting the numbering of the points is incorrect. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i16](https://cloud.githubusercontent.com/assets/13479177/26539479/4f2bced8-446a-11e7-9d79-a073a79aea18.png)

**Comment by sravanthimodepu** [comment]
Assigned the numbers in order. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #51
