### ISSUE TITLE
QA_To study the Optical Rotatory Dispersion (ORD) of some chiral substances_Quizzes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#52]
Defect Description :
In the Quiz page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, instead of giving a link, need to import the quiz unit directly by using the problem component.

Actual Result :
In the Quiz page of "To study the Optical Rotatory Dispersion (ORD) of some chiral substances" experiment in this lab, instead of giving a link, need to import the quiz unit directly by using the problem component.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i17](https://cloud.githubusercontent.com/assets/13479177/26539542/9f0d56b0-446a-11e7-9fd0-563238fa08d3.png)

**Comment by sravanthimodepu** [comment]
Ported the quiz questions in the quiz section instead of the link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #52
