### ISSUE TITLE
QA_To understand the effect of chiral substances on plane polarized light as a function of wavelength_Quizzes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#53]
Defect Description :
In the Quiz page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab, instead of giving a link, need to import the quiz unit directly by using the problem component.
The naming of the unit is given as Quiz. For other experiments the naming for the same section is given as Quizzes

Actual Result :
In the Quiz page of "To understand the effect of chiral substances on plane polarized light as a function of wavelength" experiment in this lab, instead of giving a link, need to import the quiz unit directly by using the problem component.
The naming of the unit is given as Quiz. For other experiments the naming for the same section is given as Quizzes

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i18](https://cloud.githubusercontent.com/assets/13479177/26539625/231ecb82-446b-11e7-92e3-a5de213e8a20.png)

**Comment by sravanthimodepu** [comment]
Ported the quiz separately for pre-experiment and post experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
closed #53
