### ISSUE TITLE
QA_order-of-the-menu_To study the Optical Rotatory Dispersion (ORD) of some chiral substances

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#54]
Defect Description :
The order of the menu items for this lab should be changed to "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback".

Actual Result :
The order of the menu items for this experiment is given as "Introduction, theory, objective, experiment, manual, quizzes and further readings".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i19](https://cloud.githubusercontent.com/assets/13479177/26546605/6d0f3192-4488-11e7-8220-a5bf6e0a5cdc.png)

**Comment by sravanthimodepu** [comment]
The order of menu is updated as "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback" for all the experiments. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #54
