### ISSUE TITLE
QA_To study the Circular Dichroism of some substances with chiral chromophores_Theory_spelling-mistakes 

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#55]
Defect Description :
Found spelling mistakes in the Theory section of "To study the Circular Dichroism of some substances with chiral chromophores" experiment this lab.

Actual Result :
Found spelling mistakes in the Theory section of "To study the Circular Dichroism of some substances with chiral chromophores" experiment this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i20](https://cloud.githubusercontent.com/assets/13479177/26546814/81bc1276-4489-11e7-94de-d0ed6afb4f1d.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Bug still persisted. Hence re opened the issue.

**Comment by sravanthimodepu** [comment]
Fixed.
