### ISSUE TITLE
QA_To study the Circular Dichroism of some substances with chiral chromophores_Manual_content-is-similar-to-3rd-expts-manual

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#56]
Defect Description :
In the Manual section of "To study the Circular Dichroism of some substances with chiral chromophores" experiment this lab, the content is similar to the manual's content of 3rd experiment.

Actual Result :
In the Manual section of "To study the Circular Dichroism of some substances with chiral chromophores" experiment this lab, the content is similar to the manual's content of 3rd experiment.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:

**Comment by sravanthimodepu** [comment]
Both the experiments manual has same content in the vlab.co.in.
