### ISSUE TITLE
QA_To study the Circular Dichroism of some substances with chiral chromophores_Manual_spelling-mistake

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#57]
Defect Description :
Found spelling mistakes in the Manual section of "To study the Circular Dichroism of some substances with chiral chromophores" experiment this lab.

Actual Result :
Found spelling mistakes in the Manual section of "To study the Circular Dichroism of some substances with chiral chromophores" experiment this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i21](https://cloud.githubusercontent.com/assets/13479177/26568482/6f9c8614-4521-11e7-8560-bdd463979ada.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the theory page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #57
