### ISSUE TITLE
QA_To study the Circular Dichroism of some substances with chiral chromophores_Quizzes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#58]
Defect Description :
In the Quiz page of "To study the Circular Dichroism of some substances with chiral chromophores" experiment in this lab, instead of giving a link, need to import the quiz unit directly by using the problem component.

Actual Result :
In the Quiz page of "To study the Circular Dichroism of some substances with chiral chromophores" experiment in this lab, instead of giving a link, need to import the quiz unit directly by using the problem component.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i22](https://cloud.githubusercontent.com/assets/13479177/26568540/e2c1120e-4521-11e7-871f-c3cc0d1783ef.png)

**Comment by sravanthimodepu** [comment]
Updated the quiz page with quiz questions instead of link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #58
