### ISSUE TITLE
QA_order-of-the-menu_To study the Circular Dichroism of some substances with chiral chromophores

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#59]
Defect Description :
The order of the menu items for this lab should be changed to "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback".

Actual Result :
The order of the menu items for this experiment is given as "Introduction, theory, objective, experiment, manual, quizzes and further readings".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i23](https://cloud.githubusercontent.com/assets/13479177/26568593/55ce5b76-4522-11e7-950c-58830012aa7f.png)

**Comment by sravanthimodepu** [comment]
The order of the sections are updated as "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback" in all the experiments. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #59
