### ISSUE TITLE
QA_To Study the operational details of a CD spectrometer_Theory_spelling mistakes

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#60]
Defect Description :
Found spelling mistakes in the Theory section of **To Study the operational details of a CD spectrometer** experiment this lab.

Actual Result :
Found spelling mistakes in the Theory section of **To Study the operational details of a CD spectrometer** experiment this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
Spelling mistakes are:
focussed
extraodinary
cuvet
teh

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the theory page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
The "extraodinary" spilling needs to be corrected yet. Hence re opening.

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistake. Hence resolved the issue.
