### ISSUE TITLE
QA_To Study the operational details of a CD spectrometer_Theory_improper-porting-of-images

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#61]
Defect Description :
In the Theory page of "To Study the operational details of a CD spectrometer" experiment in this lab, The images are shrunk.

Actual Result :
In the Theory page of "To Study the operational details of a CD spectrometer" experiment in this lab, The images are shrunk.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i24](https://cloud.githubusercontent.com/assets/13479177/26568752/995128fa-4523-11e7-8263-845baf6fd406.png)

**Comment by sravanthimodepu** [comment]
Aligned the image properly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #61
