### ISSUE TITLE
QA_order-of-the-menu_To Study the operational details of a CD spectrometer

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#62]
Defect Description :
The order of the menu items for this lab should be changed to "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback".

Actual Result :
The order of the menu items for this experiment is given as "Introduction, theory, objective, experiment, manual, quizzes and further readings".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i26](https://cloud.githubusercontent.com/assets/13479177/26569382/01ba5eda-4528-11e7-9117-d19f1d5e89f8.png)

**Comment by sravanthimodepu** [comment]
The order of sections are updated as "Introduction, Objective, Theory, Manual, Experiment, Quizzes, Further Readings and Feedback". Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #62
