### ISSUE TITLE
QA_To Study the effect of Secondary Structure elements on CD spectrum of proteins_unwanted-and-repeated-sub-sections

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#63]
Defect Description :
In the menu of the **To Study the effect of Secondary Structure elements on CD spectrum of proteins** experiment of this lab, found unwanted and repeated sub-sections. Need to remove the subsection which have been repeatedly ported. 

Actual Result :
In the menu of the **To Study the effect of Secondary Structure elements on CD spectrum of proteins** experiment of this lab, found unwanted and repeated sub-sections. Need to remove the subsection which have been repeatedly ported.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i27](https://cloud.githubusercontent.com/assets/13479177/26569511/bdcae748-4528-11e7-91b1-0baa62b26fe5.png)

**Comment by sravanthimodepu** [comment]
Removed unwanted and repeated sub-sections from the experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #63
