### ISSUE TITLE
QA_To Study the effect of Secondary Structure elements on CD spectrum of proteins_Introduction_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#64]
Defect Description :
Found spelling mistakes in the Introduction section of **To Study the effect of Secondary Structure elements on CD spectrum of proteins** experiment this lab.

Actual Result :
Found spelling mistakes in the Introduction section of **To Study the effect of Secondary Structure elements on CD spectrum of proteins** experiment this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i28](https://cloud.githubusercontent.com/assets/13479177/26569605/3fa92ee6-4529-11e7-9657-38a827f909c2.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the Introduction page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
The bug is still persisted. Hence re opening the issue.

**Comment by sravanthimodepu** [comment]
Fixed.

**Comment by BSravanthi** [comment]
Closed #64
