### ISSUE TITLE
QA_To Study the effect of Secondary Structure elements on CD spectrum of proteins_Theory_unwanted-boxes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#65]
Defect Description :
In the Theory section of the To Study the effect of Secondary Structure elements on CD spectrum of proteins experiment of this lab, while porting the section the tiles in the sections are ported in a boxes. Where as in vlabs page we do not find these boxes for the titles.

Actual Result :
In the Theory section of the To Study the effect of Secondary Structure elements on CD spectrum of proteins experiment of this lab, while porting the section the tiles in the sections are ported in a boxes. Where as in vlabs page we do not find these boxes for the titles.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i29](https://cloud.githubusercontent.com/assets/13479177/26570956/e080005e-4530-11e7-89d6-2d8cb8a9dceb.png)

**Comment by sravanthimodepu** [comment]
Removed all the unwanted boxes from the theory page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #65
