### ISSUE TITLE
QA_To Study the effect of Secondary Structure elements on CD spectrum of proteins_Theory_improper-alignment-of-boxes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#66]
Defect Description :
In the Theory section of the To Study the effect of Secondary Structure elements on CD spectrum of proteins experiment of this lab, while porting, the alignment of the  image boxes is improper. The boxes are extended more than the image.

Actual Result :
In the Theory section of the To Study the effect of Secondary Structure elements on CD spectrum of proteins experiment of this lab, while porting, the alignment of the  image boxes is improper. The boxes are extended more than the image.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i30](https://cloud.githubusercontent.com/assets/13479177/26571120/d9a4115c-4531-11e7-826b-d9b3cf961f31.png)

**Comment by sravanthimodepu** [comment]
As the images were given inside the table tags, they are displaying in the box. Hence, removed the table tags for the images and resolved the issue.

**Comment by BSravanthi** [comment]
Closed #66
