### ISSUE TITLE
QA_To Study the effect of Secondary Structure elements on CD spectrum of proteins_Quizzes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#67]
Defect Description :
In the Quiz page of "To Study the effect of Secondary Structure elements on CD spectrum of proteins" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Actual Result :
In the Quiz page of "To Study the effect of Secondary Structure elements on CD spectrum of proteins" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i31](https://cloud.githubusercontent.com/assets/13479177/26571871/65da34f0-4535-11e7-94c8-1e9fa10d00c0.png)

**Comment by sravanthimodepu** [comment]
Updated the quiz separately for both pre experiment and post experiment in the quiz section instead of links. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #67
