### ISSUE TITLE
QA_order-of-the-menu_To Study the effect of Secondary Structure elements on CD spectrum of proteins

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#68]
Defect Description :
The order of the menu items for this lab should be changed to "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback".

Actual Result :
The order of the menu items for this experiment is given as "Introduction, theory, objective, experiment, manual, quizzes and further readings".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i27](https://cloud.githubusercontent.com/assets/13479177/26571990/da253b5c-4535-11e7-8ab0-e9e6f85bc8e2.png)

**Comment by sravanthimodepu** [comment]
The order of the menu is updated as  "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback". Hence resolved the issue.

**Comment by BSravanthi** [comment]
The bus is still persisted. Hence reopened the issue.

**Comment by sravanthimodepu** [comment]
Corrected the menu.

**Comment by BSravanthi** [comment]
Closed #68
