### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_all-sections_bread-crump-overlaps-the-bookmark-button

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#69]
Defect Description :
In all the sections of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, the bread crump is overlapping the bookmarks button. 

Actual Result :
In all the sections of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, the bread crump is overlapping the bookmarks button. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i32](https://cloud.githubusercontent.com/assets/13479177/26572271/f2e7ad7c-4536-11e7-9c6b-cb2837ed8ec9.png)

**Comment by sravanthimodepu** [comment]
Issue is keeping on hold.
