### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Theory_improper-alignment-of-boxes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#70]
Defect Description :
In the Theory section of the **To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements** experiment of this lab, while porting, the alignment of the image boxes were not ported properly. The boxes are extended more than the image. This is effecting the look and feel of the page.

Actual Result :
In the Theory section of the **To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements** experiment of this lab, while porting, the alignment of the image boxes were not ported properly. The boxes are extended more than the image. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds-i32](https://cloud.githubusercontent.com/assets/13479177/26572438/93699468-4537-11e7-817c-25e8e384adcd.png)

**Comment by sravanthimodepu** [comment]
As the Images in the theory page are given inside the table tags, removed the table tags for the images to view correctly.  Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #70
