### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Theory_Broken-links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#71]
Defect Description :
In the Theory page of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, the Experiment6 link is redirecting to an error page showing "Page not found". Where as the links should redirect to the appropriate pages.

Actual Result :
In the Theory page of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, the Experiment6 link is redirecting to an error page showing "Page not found".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds-i33](https://cloud.githubusercontent.com/assets/13479177/26572674/76bf7d5e-4538-11e7-9e35-8e0623158931.png)

**Comment by sravanthimodepu** [comment]
Assigned appropriate link for the above mentioned link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #71
