### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Manual_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#72]
Defect Description :
Found spelling mistakes in the Manual section of **To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements** experiment this lab.

Actual Result :
Found spelling mistakes in the Manual section of **To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements** experiment this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds-i34](https://cloud.githubusercontent.com/assets/13479177/26572836/09d7a0da-4539-11e7-8fa8-2d7e519e4efa.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the manual page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Re opening the issue as one more spelling needs to be corrected. 

![qa_oe_cds_i85](https://user-images.githubusercontent.com/13479177/27675419-92765030-5cc7-11e7-8bd5-66503abb8dc0.png)

**Comment by sravanthimodepu** [comment]
As the "deconvolute" spelling is correct, differing the issue.

**Comment by BSravanthi** [comment]
Not a differed issue.
