### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Quizzes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#73]
Defect Description :
In the Quiz page of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Actual Result :
In the Quiz page of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i35](https://cloud.githubusercontent.com/assets/13479177/26574916/daeb8ca2-4540-11e7-98fb-5c8b677303ca.png)

**Comment by sravanthimodepu** [comment]
Ported the quiz separately for post experiment & pre experiment in the quiz section instead of links. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #73
