### ISSUE TITLE
QA_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements_Further readings_unassigned-links

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#74]
Defect Description :
In the further References page of "To deconvolute the CD spectrum of a given protein solution and to 
classify it in terms of its secondary structure elements" experiment in this lab, the 2nd link in the 2nd point is unassigned. Where as in vlabs page the link is assigned and navigating to concerned page. 

Actual Result :
In the further References page of "To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements" experiment in this lab, the 2nd link in the 2nd point is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i36](https://cloud.githubusercontent.com/assets/13479177/26575138/96a961da-4541-11e7-9225-d7b7fe4aecc9.png)

**Comment by sravanthimodepu** [comment]
Tried to assign appropriate link for the 2nd link, as it is redirecting to error page, comment the link and updated the page.

**Comment by BSravanthi** [comment]
Closed #74
