### ISSUE TITLE
QA_order-of-the-menu_To deconvolute the CD spectrum of a given protein solution and to classify it in terms of its secondary structure elements

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#75]
Defect Description :
The order of the menu items for this lab should be changed to "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback".

Actual Result :
The order of the menu items for this experiment is given as "Introduction, theory, objective, experiment, manual, quizzes and further readings".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i37](https://cloud.githubusercontent.com/assets/13479177/26575246/0ed9e1de-4542-11e7-8253-efa19cc2ddbc.png)

**Comment by sravanthimodepu** [comment]
The order of the menu is updated as "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback". Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #75
