### ISSUE TITLE
QA_To Study the Thermal Stability of Proteins_Theory

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#76]
Defect Description :
In the Theory page of "To Study the Thermal Stability of Proteins" experiment in this lab, the headings needs to be highlighted.
 
Actual Result :
In the Theory page of "To Study the Thermal Stability of Proteins" experiment in this lab, the headings needs to be highlighted.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i39](https://cloud.githubusercontent.com/assets/13479177/26576336/2465f7aa-4546-11e7-9e99-0e2d58c99ef6.png)

**Comment by sravanthimodepu** [comment]
Aligned the paragraph and headings properly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue still persists. Hence reopening the issue.

**Comment by sravanthimodepu** [comment]
Differing the issue, as it wa
![therm-stab](https://user-images.githubusercontent.com/11156924/27791102-10358cb0-6011-11e7-8782-1baba3e1902e.png)
s fixed.

**Comment by BSravanthi** [comment]
Closed #76
