### ISSUE TITLE
QA_To Study the Thermal Stability of Proteins_Quiz

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#78]
Defect Description :
In the Quiz page of "To Study the Thermal Stability of Proteins" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Actual Result :
In the Quiz page of "To Study the Thermal Stability of Proteins" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i41](https://cloud.githubusercontent.com/assets/13479177/26576949/44c8039c-4548-11e7-8d1c-5e60ef1123f2.png)

**Comment by sravanthimodepu** [comment]
Updated the quiz questions in the quiz section, instead of link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #78
