### ISSUE TITLE
QA_To Study the Thermal Stability of Proteins_Quiz-2

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#79]
Defect Description :
The name of the quizzes section is given as Quiz in the **To Study the Thermal Stability of Proteins** experiment. To maintain consistency with other experiments, the naming should be same. 

Actual Result :
The name of the quizzes section is given as Quiz in the **To Study the Thermal Stability of Proteins** experiment. To maintain consistency with other experiments, the naming should be same.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i42](https://cloud.githubusercontent.com/assets/13479177/26577095/d39b252c-4548-11e7-9107-656a18f016de.png)

**Comment by sravanthimodepu** [comment]
The naming of the quiz section is updated as **Quiz** and given same for the experiments. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #79
