### ISSUE TITLE
QA_order-of-the-menu_To study the thermal stability of proteins

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#80]
Defect Description :
The order of the menu items for this lab should be changed to "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback".

Actual Result :
The order of the menu items for this experiment is given as "Introduction, theory, objective, experiment, manual, quizzes and further readings".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i42](https://cloud.githubusercontent.com/assets/13479177/26577323/a77a17c2-4549-11e7-813a-980a8e2659e6.png)

**Comment by sravanthimodepu** [comment]
The order of the menu items for this experiment is updated as "Introduction, theory, objective, experiment, manual, quizzes and further readings". Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #80
