### ISSUE TITLE
QA_To study the effect of chemical denaturants on protein stability_Theory

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#82]
Defect Description :
In the Theory page of "To study the effect of chemical denaturants on protein stability" experiment in this lab, the headings needs to be highlighted.

Actual Result :
In the Theory page of "To study the effect of chemical denaturants on protein stability" experiment in this lab, the headings needs to be highlighted.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i44](https://cloud.githubusercontent.com/assets/13479177/26578315/fd36d18e-454c-11e7-9e7c-46fd1f7ecf37.png)

**Comment by sravanthimodepu** [comment]
Aligned the paragraphs and headings properly in the theory page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #82
