### ISSUE TITLE
QA_To study the effect of chemical denaturants on protein stability_Quiz

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#84]
Defect Description :
In the Quiz page of "To study the effect of chemical denaturants on protein stability" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Actual Result :
In the Quiz page of "To study the effect of chemical denaturants on protein stability" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i46](https://cloud.githubusercontent.com/assets/13479177/26578800/ee7409b2-454e-11e7-816d-b20dcdf17979.png)

**Comment by sravanthimodepu** [comment]
Quiz questions are ported directly in the quiz unit, instead of quiz link and assigned proper numbering for the questions. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #84
