### ISSUE TITLE
QA_To study the effect of chemical denaturants on protein stability_Quiz-2

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#85]
Defect Description :
The name of the quizzes section is given as Quiz in the To study the effect of chemical denaturants on protein stability experiment. To maintain consistency with other experiments, the naming should be same.

Actual Result :
The name of the quizzes section is given as Quiz in the To Study the To study the effect of chemical denaturants on protein stability experiment. To maintain consistency with other experiments, the naming should be same.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i47](https://cloud.githubusercontent.com/assets/13479177/26578899/554bd8fe-454f-11e7-9ee3-c92e9166969f.png)

**Comment by sravanthimodepu** [comment]
The naming of the quiz section is given as **Quiz** in all the experiments. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #85
