### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents_Introduction-objective-Manual_bread-crump-overlaps-the-bookmark-button

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#87]
Defect Description :
In the introduction, objective and Manual sections of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, the bread crump is overlapping the bookmarks button.

Actual Result :
In the introduction, objective and Manual sections of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, the bread crump is overlapping the bookmarks button.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i48](https://cloud.githubusercontent.com/assets/13479177/26579177/55f11642-4550-11e7-8f9d-2704638c3e37.png)

**Comment by sravanthimodepu** [comment]
Issue is on hold. System's team need to work on this issue.
