### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents_objective_2-units-are-visible

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#88]
Defect Description :
In the objective section of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, two units are visible, with in which one unit is unwanted. The unwanted unit contains no content. 

Actual Result :
In the objective section of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, two units are visible, with in which one unit is unwanted. The unwanted unit contains no content. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i49](https://cloud.githubusercontent.com/assets/13479177/26579516/cbec36c8-4551-11e7-89d9-6431caacfe7c.png)

**Comment by sravanthimodepu** [comment]
Removed the extra unit from the objective. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #88
