### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents _Manual_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#90]
Defect Description :
Found spelling mistakes in the Manual section of **To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents** experiment of this lab.

Actual Result :
Found spelling mistakes in the Manual section of **To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents** experiment of this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i51](https://cloud.githubusercontent.com/assets/13479177/26579769/ddb596f0-4552-11e7-8bb8-336fc5d12804.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the manual page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #90
