### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents _Quizzes_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#91]
Defect Description :
Found spelling mistakes in the Quiz section of **To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents** experiment of this lab.

Actual Result :
Found spelling mistakes in the Quiz section of **To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents** experiment of this lab.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i52](https://cloud.githubusercontent.com/assets/13479177/26579845/43b8c512-4553-11e7-9891-305dc5fb62f8.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling to **Emission** in the quiz. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #91
