### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents _Quiz

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#92]
Defect Description :
In the Quiz page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Actual Result :
In the Quiz page of "To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents" experiment in this lab, instead of giving a links, need to import the quiz unit directly by using the problem component.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i53](https://cloud.githubusercontent.com/assets/13479177/26579924/93e80c0a-4553-11e7-86d8-0dad72f6d47d.png)

**Comment by sravanthimodepu** [comment]
Ported the quiz questions in the quiz unit instead of link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #92
