### ISSUE TITLE
QA_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents _Quiz-2

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#93]
Defect Description :
The name of the quizzes section is given as Quiz in the **To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents** experiment. To maintain consistency with other experiments, the naming should be same.

Actual Result :
The name of the quizzes section is given as Quiz in the **To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents** experiment. To maintain consistency with other experiments, the naming should be same.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i54](https://cloud.githubusercontent.com/assets/13479177/26579996/dbdd098e-4553-11e7-9bdd-a85de3450a73.png)

**Comment by sravanthimodepu** [comment]
The naming of quiz is given same for all the experiments. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #93
