### ISSUE TITLE
QA_order-of-the-menu_To study the comparison between protein unfolding and protein aggregation in the presence of chemical denaturing agents

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#94]
Defect Description :
The order of the menu items for this lab should be changed to "Introduction, Objective, theory, Manual, Experiment, Quizzes, Further Readings and Feedback".

Actual Result :
The order of the menu items for this experiment is given as "Introduction, theory, objective, experiment, manual, quizzes and further readings".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i54](https://cloud.githubusercontent.com/assets/13479177/26580285/0af1e6d0-4555-11e7-8240-cffe3aa96072.png)

**Comment by sravanthimodepu** [comment]
The order of the menu items for this experiment is given as "Introduction, theory, objective, experiment, manual, quizzes and further readings". Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #94
