### ISSUE TITLE
QA_To study the Optical Rotatory Dispersion (ORD) of some chiral substances_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#98]
Defect Description :
In the To study the Optical Rotatory Dispersion (ORD) of some chiral substances experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the To study the Optical Rotatory Dispersion (ORD) of some chiral substances experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i57](https://cloud.githubusercontent.com/assets/13479177/26709842/4fb7b2a2-4773-11e7-9f9a-ab37f6f04dad.png)

**Comment by sravanthimodepu** [comment]
Simulation is displaying on the small screen. Hence differing the issue.
![opt-rot](https://user-images.githubusercontent.com/11156924/27767608-4dbb30f0-5f1a-11e7-9c77-d7ed6ff786ab.png)

**Comment by BSravanthi** [comment]
Not a differed issue. Though the experiment works with java or not it does not make any difference in enabling the small screen.

**Comment by BSravanthi** [comment]
Closed #98 as the issue got resolved.
