### ISSUE TITLE
QA_To study the Circular Dichroism of some substances with chiral chromophores_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/circular-dichronism-spectroscopy-iiith#99]
Defect Description :
In the "To study the Circular Dichroism of some substances with chiral chromophores" experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Actual Result :
In the **To study the Circular Dichroism of some substances with chiral chromophores** experiment, the assessment is disabled in the small screen. Instead, the assessment should function in both full and small screens.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_cds_i59](https://cloud.githubusercontent.com/assets/13479177/26710619/e06c8c46-4778-11e7-85ca-5162d966a827.png)

**Comment by sravanthimodepu** [comment]
Simulation is displaying on the small screen. Hence differing the issue.
![chromo](https://user-images.githubusercontent.com/11156924/27767697-009eec1e-5f1d-11e7-88d9-fe8553f8bb1f.png)

**Comment by BSravanthi** [comment]
Not a differed issue. Though the experiment works with java or not it does not make any difference in enabling the small screen.

**Comment by BSravanthi** [comment]
Closed #99 as the issue got resolved.
